### ISSUE TITLE
The x and y coordinates are most likely inverted

### ISSUE THREAD

**Issue by tpoisot** [EcoJulia/SpatialBoundaries.jl#32]
This isn't a "bug" bug, more like something counter-intuitive, but when it comes to plotting, `x` and `y` are actually the opposite of what we expect - either this needs to be documented better, or changed.

**Comment by TanyaS08** [comment]
should we add this to the wombling() doc string or do you think it is sufficient to address in the intro vignette?

**Comment by tpoisot** [comment]
Not everyone will look at the vignettes so let's put this in a docstring? Maybe this should go in the type docstring?
