### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by tpoisot** [EcoJulia/SpatialBoundaries.jl#37]
The current logo is a screenshot of a map -- @TanyaS08 mentioned she had something better in mind.

All that's needed is a square transparent png at `docs/src/assets/logo.png` (600 dpi would slap)

**Comment by TanyaS08** [comment]
![logo2](https://user-images.githubusercontent.com/61696728/150577138-61d8a7a6-1102-4341-8793-80f5e39f5fbe.png)
![logo](https://user-images.githubusercontent.com/61696728/150577205-59637bd9-8c14-450d-8118-b191ad5bf38b.png)

**Comment by TanyaS08** [comment]
I'm conflicted...

**Comment by tpoisot** [comment]
1st

**Comment by TanyaS08** [comment]
![logo_2](https://user-images.githubusercontent.com/61696728/151872497-0f9d9579-46fe-4c33-a411-9d5c1901fe35.png)

**Comment by TanyaS08** [comment]
After extensive feedback there has been another proposal
